-- MySQL Script generated by MySQL Workbench
-- Sat Jan 10 18:56:35 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`oposiciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`oposiciones` (
  `id_oposicion` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_oposicion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pruebas_oficiales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pruebas_oficiales` (
  `id_pruebas_oficiales` INT NOT NULL AUTO_INCREMENT,
  `nombre_prueba` VARCHAR(200) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `trucos` TEXT NULL,
  `oposiciones_id_oposicion` INT NOT NULL,
  `mejor_si_es_menor` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_pruebas_oficiales`),
  INDEX `fk_pruebas_oficiales_oposiciones1_idx` (`oposiciones_id_oposicion` ASC) VISIBLE,
  CONSTRAINT `fk_pruebas_oficiales_oposiciones1`
    FOREIGN KEY (`oposiciones_id_oposicion`)
    REFERENCES `mydb`.`oposiciones` (`id_oposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `genero` ENUM('MUJER', 'HOMBRE') NOT NULL,
  `peso` DECIMAL(10,2) NOT NULL,
  `altura` DECIMAL(10,2) NOT NULL,
  `imc` DECIMAL(10,2) NULL,
  `fecha_registro` DATETIME NOT NULL,
  `oposiciones_id_oposicion` INT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_usuarios_oposiciones1_idx` (`oposiciones_id_oposicion` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_oposiciones1`
    FOREIGN KEY (`oposiciones_id_oposicion`)
    REFERENCES `mydb`.`oposiciones` (`id_oposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marcas_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marcas_perfil` (
  `id_marcas_perfil` INT NOT NULL AUTO_INCREMENT,
  `valord_record` DECIMAL(10,2) NOT NULL,
  `fecha_logro` DATETIME NOT NULL,
  `pruebas_oficiales_id_pruebas_oficiales` INT NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_marcas_perfil`),
  INDEX `fk_marcas_perfil_pruebas_oficiales1_idx` (`pruebas_oficiales_id_pruebas_oficiales` ASC) VISIBLE,
  INDEX `fk_marcas_perfil_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_marcas_perfil_pruebas_oficiales1`
    FOREIGN KEY (`pruebas_oficiales_id_pruebas_oficiales`)
    REFERENCES `mydb`.`pruebas_oficiales` (`id_pruebas_oficiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_marcas_perfil_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutinas_pers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutinas_pers` (
  `id_rutina_pers` INT NOT NULL AUTO_INCREMENT,
  `nombre_personalizado` VARCHAR(200) NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_rutina_pers`),
  INDEX `fk_rutinas_pers_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_pers_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutinas_opo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutinas_opo` (
  `id_rutina_opo` INT NOT NULL AUTO_INCREMENT,
  `nivel` ENUM('BASICO', 'INTERMEDIO', 'AVANZADO') NOT NULL,
  `genero` ENUM('HOMBRE', 'MUJER') NOT NULL,
  `enfoque_tipo` ENUM('FUERZA', 'VELOCIDAD', 'RESISTENCIA') NOT NULL,
  `oposiciones_id_oposicion` INT NOT NULL,
  PRIMARY KEY (`id_rutina_opo`),
  INDEX `fk_rutinas_opo_oposiciones1_idx` (`oposiciones_id_oposicion` ASC) VISIBLE,
  CONSTRAINT `fk_rutinas_opo_oposiciones1`
    FOREIGN KEY (`oposiciones_id_oposicion`)
    REFERENCES `mydb`.`oposiciones` (`id_oposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`historial_sesiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`historial_sesiones` (
  `id_historial_sesion` INT NOT NULL AUTO_INCREMENT,
  `fecha_entreno` DATETIME NOT NULL,
  `tipo_rutina` ENUM('OPO', 'PERS') NOT NULL,
  `duracion_oficial` INT NOT NULL,
  `rutinas_pers_id_rutina_pers` INT NULL,
  `rutinas_opo_id_rutina_opo` INT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_historial_sesion`),
  INDEX `fk_historial_sesiones_rutinas_pers1_idx` (`rutinas_pers_id_rutina_pers` ASC) VISIBLE,
  INDEX `fk_historial_sesiones_rutinas_opo1_idx` (`rutinas_opo_id_rutina_opo` ASC) VISIBLE,
  INDEX `fk_historial_sesiones_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_historial_sesiones_rutinas_pers1`
    FOREIGN KEY (`rutinas_pers_id_rutina_pers`)
    REFERENCES `mydb`.`rutinas_pers` (`id_rutina_pers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_sesiones_rutinas_opo1`
    FOREIGN KEY (`rutinas_opo_id_rutina_opo`)
    REFERENCES `mydb`.`rutinas_opo` (`id_rutina_opo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_historial_sesiones_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ejercicios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ejercicios` (
  `id_ejercicio` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(200) NOT NULL,
  `video_url` VARCHAR(255) NULL,
  `instrucciones_tecnicas` TEXT NULL,
  PRIMARY KEY (`id_ejercicio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`requisitos_nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`requisitos_nivel` (
  `id_requisito_nivel` INT NOT NULL AUTO_INCREMENT,
  `genero` ENUM('HOMBRE', 'MUJER') NOT NULL,
  `nivel_exigencia` INT NOT NULL,
  `valor_objetivo` DECIMAL(10,2) NOT NULL,
  `pruebas_oficiales_id_pruebas_oficiales` INT NOT NULL,
  PRIMARY KEY (`id_requisito_nivel`),
  INDEX `fk_requisitos_nivel_pruebas_oficiales1_idx` (`pruebas_oficiales_id_pruebas_oficiales` ASC) VISIBLE,
  CONSTRAINT `fk_requisitos_nivel_pruebas_oficiales1`
    FOREIGN KEY (`pruebas_oficiales_id_pruebas_oficiales`)
    REFERENCES `mydb`.`pruebas_oficiales` (`id_pruebas_oficiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mydb`.`baremos_puntuacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`baremos_puntuacion` (
  `id_baremo` INT NOT NULL AUTO_INCREMENT,
  `pruebas_oficiales_id_pruebas_oficiales` INT NOT NULL,
  `genero` ENUM('H', 'M') NOT NULL,
  `marca_valor` DECIMAL(10,2) NOT NULL,
  `nota` INT NOT NULL,
  PRIMARY KEY (`id_baremo`),
  CONSTRAINT `fk_baremo_prueba`
    FOREIGN KEY (`pruebas_oficiales_id_pruebas_oficiales`)
    REFERENCES `mydb`.`pruebas_oficiales` (`id_pruebas_oficiales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `mydb`.`noticias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`noticias` (
  `id_noticia` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(500) NOT NULL,
  `contenido` TEXT NOT NULL,
  `fecha_publicacion` DATETIME NOT NULL,
  `oposiciones_id_oposicion` INT NOT NULL,
  PRIMARY KEY (`id_noticia`),
  INDEX `fk_noticias_oposiciones_idx` (`oposiciones_id_oposicion` ASC) VISIBLE,
  CONSTRAINT `fk_noticias_oposiciones`
    FOREIGN KEY (`oposiciones_id_oposicion`)
    REFERENCES `mydb`.`oposiciones` (`id_oposicion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`settings` (
  `id_setting` INT NOT NULL AUTO_INCREMENT,
  `unidad_peso` VARCHAR(20) NOT NULL,
  `unidad_distancia` VARCHAR(20) NOT NULL,
  `usuarios_id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_setting`),
  INDEX `fk_settings_usuarios1_idx` (`usuarios_id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_settings_usuarios1`
    FOREIGN KEY (`usuarios_id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_rutina_opo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_rutina_opo` (
  `ejercicios_id_ejercicio` INT NOT NULL,
  `rutinas_opo_id_rutina_opo` INT NOT NULL,
  `id_detalle_rutina_opo` INT NOT NULL AUTO_INCREMENT,
  `repeticiones` INT NOT NULL,
  `series` INT NOT NULL,
  `descanso` INT NOT NULL,
  INDEX `fk_ejercicios_has_rutinas_opo_rutinas_opo1_idx` (`rutinas_opo_id_rutina_opo` ASC) VISIBLE,
  INDEX `fk_ejercicios_has_rutinas_opo_ejercicios1_idx` (`ejercicios_id_ejercicio` ASC) VISIBLE,
  PRIMARY KEY (`id_detalle_rutina_opo`),
  CONSTRAINT `fk_ejercicios_has_rutinas_opo_ejercicios1`
    FOREIGN KEY (`ejercicios_id_ejercicio`)
    REFERENCES `mydb`.`ejercicios` (`id_ejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ejercicios_has_rutinas_opo_rutinas_opo1`
    FOREIGN KEY (`rutinas_opo_id_rutina_opo`)
    REFERENCES `mydb`.`rutinas_opo` (`id_rutina_opo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`detalle_rutina_pers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`detalle_rutina_pers` (
  `rutinas_pers_id_rutina_pers` INT NOT NULL,
  `ejercicios_id_ejercicio` INT NOT NULL,
  `series` INT NOT NULL,
  `repeticiones` INT NOT NULL,
  `id_detalle_rutina_pers` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_rutinas_pers_has_ejercicios_ejercicios1_idx` (`ejercicios_id_ejercicio` ASC) VISIBLE,
  INDEX `fk_rutinas_pers_has_ejercicios_rutinas_pers1_idx` (`rutinas_pers_id_rutina_pers` ASC) VISIBLE,
  PRIMARY KEY (`id_detalle_rutina_pers`),
  CONSTRAINT `fk_rutinas_pers_has_ejercicios_rutinas_pers1`
    FOREIGN KEY (`rutinas_pers_id_rutina_pers`)
    REFERENCES `mydb`.`rutinas_pers` (`id_rutina_pers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_rutinas_pers_has_ejercicios_ejercicios1`
    FOREIGN KEY (`ejercicios_id_ejercicio`)
    REFERENCES `mydb`.`ejercicios` (`id_ejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registro_resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`registro_resultados` (
  `ejercicios_id_ejercicio` INT NOT NULL,
  `historial_sesiones_id_historial_sesiones` INT NOT NULL,
  `id_resultado` INT NOT NULL AUTO_INCREMENT,
  `valor_conseguido` DECIMAL(10,2) NOT NULL,
  INDEX `fk_ejercicios_has_historial_sesiones_historial_sesiones1_idx` (`historial_sesiones_id_historial_sesiones` ASC) VISIBLE,
  INDEX `fk_ejercicios_has_historial_sesiones_ejercicios1_idx` (`ejercicios_id_ejercicio` ASC) VISIBLE,
  PRIMARY KEY (`id_resultado`),
  CONSTRAINT `fk_ejercicios_has_historial_sesiones_ejercicios1`
    FOREIGN KEY (`ejercicios_id_ejercicio`)
    REFERENCES `mydb`.`ejercicios` (`id_ejercicio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ejercicios_has_historial_sesiones_historial_sesiones1`
    FOREIGN KEY (`historial_sesiones_id_historial_sesiones`)
    REFERENCES `mydb`.`historial_sesiones` (`id_historial_sesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
